### ISSUE TITLE
Rec cannot use RxJS because cannot initialize global context

### ISSUE THREAD

**Issue by kenpusney** [rec-framework/rec-core#44]
Rec get following error while loading and running rx.js:
```
=> Rec v2
Exception in thread "main" org.mozilla.javascript.JavaScriptException: Error: RxJS could not find any global context (window, self, global) (rx#34)
        at org.mozilla.javascript.gen.rx_3._c_anonymous_2(rx:34)
        at org.mozilla.javascript.gen.rx_3.call(rx)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.rx_3._c_anonymous_1(rx:20)
        at org.mozilla.javascript.gen.rx_3.call(rx)
        at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
        at org.mozilla.javascript.gen.rx_3._c_script_0(rx:20)
        at org.mozilla.javascript.gen.rx_3.call(rx)
        at org.mozilla.javascript.gen.rx_3.exec(rx)
        at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:342)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:290)
        at org.mozilla.javascript.commonjs.module.Require.call(Require.java:219)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.abc_js_2._c_script_0(abc.js:1)
        at org.mozilla.javascript.gen.abc_js_2.call(abc.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
        at org.mozilla.javascript.gen.abc_js_2.call(abc.js)
        at org.mozilla.javascript.gen.abc_js_2.exec(abc.js)
        at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:342)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:290)
        at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
        at net.kimleo.rec.v2.scripting.Scripting.runReader(Scripting.java:34)
        at net.kimleo.rec.v2.scripting.Scripting.runfile(Scripting.java:22)
        at net.kimleo.rec.App.execute(App.java:66)
        at net.kimleo.rec.App.main(App.java:28)
```

Discovered when spike #34

**Comment by kenpusney** [comment]
https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.4.0/Rx.min.js
