### ISSUE TITLE
JSON.stringify for POJO

### ISSUE THREAD

**Issue by kenpusney** [rec-framework/rec-core#53]

**Comment by kenpusney** [comment]
```
org.mozilla.javascript.EvaluatorException: Java class "[Ljava.lang.reflect.Constructor;" has no public instance field or method named "toJSON". (resource/330#4)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:954)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1010)
        at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:980)
        at org.mozilla.javascript.NativeJavaArray.get(NativeJavaArray.java:67)
        at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
        at org.mozilla.javascript.NativeJSON.str(NativeJSON.java:280)
        at org.mozilla.javascript.NativeJSON.jo(NativeJSON.java:361)
        at org.mozilla.javascript.NativeJSON.str(NativeJSON.java:324)
        at org.mozilla.javascript.NativeJSON.jo(NativeJSON.java:361)
        at org.mozilla.javascript.NativeJSON.str(NativeJSON.java:324)
        at org.mozilla.javascript.NativeJSON.jo(NativeJSON.java:361)
        at org.mozilla.javascript.NativeJSON.str(NativeJSON.java:324)
        at org.mozilla.javascript.NativeJSON.stringify(NativeJSON.java:266)
        at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:101)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.resource_330_8._c_script_0(resource/330:4)
        at org.mozilla.javascript.gen.resource_330_8.call(resource/330)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
        at org.mozilla.javascript.gen.resource_330_8.call(resource/330)
        at org.mozilla.javascript.gen.resource_330_8.exec(resource/330)
        at org.mozilla.javascript.commonjs.module.Require.executeModuleScript(Require.java:342)
        at org.mozilla.javascript.commonjs.module.Require.getExportedModuleInterface(Require.java:290)
        at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:137)
        at net.kimleo.rec.cloud.context.scripting.Scripting.execute(Scripting.java:53)
        at net.kimleo.rec.cloud.context.scripting.Scripting.runHostedModule(Scripting.java:45)
        at net.kimleo.rec.cloud.manager.service.ScriptingService.runHostedModule(ScriptingService.java:22)
        at net.kimleo.rec.cloud.manager.controller.HostedController.hostedGetHandler(HostedController.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
```

**Comment by kenpusney** [comment]
using org.json:json
